---
title: "Study1 Discussion"
output:
  bookdown::html_document2:
  bookdown::word_document2:
    reference_docx: "/home/rstudio/NuisanceStudy/reference/document_template.docx"
suppress-bibliography: yes
# bibliography: "/home/rstudio/NuisanceStudy/reference/references.bib"
# csl: "/home/rstudio/NuisanceStudy/reference/apa.csl"
---

研究1の目的は，無神経であること自体が，その人物への印象に与える影響を検討することであった。実験の結果，仮説1と2は支持された。つまり，無神経な人物に対して，その人物の実際の行動よりも無神経であることに重きを置いて，否定的印象を形成することが示された。

研究1の問題は，判断対象人物の全体的な望ましさが，使用した評価項目への回答に交絡している可能性を認められることである。特に，迷惑行為を実行しなかった場合と比較して，実行した場合では，迷惑を理解している人物と理解していない人物に対する能力評価の差が小さくなった。この理由の1つは，自身の行動が迷惑行為に当たると理解していて，なおもそれを実行する人物を，全体的にネガティブに評価したためであると考える。また，研究1で用いた能力に関する評価項目が能力一般に関する広範なものであったことの影響も想定できる。無神経さが示唆するものが特に知的能力の低さである場合，研究1で用いた能力全般に関する評価項目は不適当であり，そのために無神経な人物の能力が低く評価される効果が小さくなった可能性がある。他にも，同一の参加者が迷惑への理解の有無の両条件で回答を行っているため，理解に関する条件間の差異が強調され，この要因の効果が実際以上に大きくなっている可能性がある。

研究2では，これらの問題に対処するため，迷惑への理解の有無の操作を参加者間で行い，各参加者は判断対象人物の迷惑への理解について1つの条件のみを呈示されるように変更する。そして，知的能力に絞った測定項目を用いることを中心に，人物評価に関する項目を修正し，仮説1と仮説2を改めて検証する。また，判断対象人物を冷たいと評価することを通して，将来的に迷惑行為を実行しやすいと考えることが，その人物に対する社会的距離と非難の増大を予測することを検証する。なお，電子付録に記載した研究2の予備的研究では，この仮説を概ね支持する結果が得られている。さらに，動物的非人間化を検討対象に加えることで，無神経な人物の知的能力を低く見積もることによる侮蔑的な評価をより直接的に検討する。これらにより，無神経な人物への認知に関して，印象形成に加え，人間性の評価と態度形成の観点からも検討する。

