---
title: "Vignettes"
output:
  bookdown::word_document2: 
    number_sections: false
    reference_docx: "/home/rstudio/NuisanceStudy/reference/document_template.docx"
  bookdown::html_document2: default 
link-citations: yes
editor_options:
  chunk_output_type: console
# bibliography: "/home/rstudio/NuisanceStudy/reference/references.bib"
# csl: "/home/rstudio/NuisanceStudy/reference/apa.csl"
---

2020年度駅と電車内の迷惑行為ランキング [@mintetsu2021meiwakurank] のうち，電車内での迷惑行為上位3つを題材として，迷惑行為の実行に関与する人物が1人に限定されるような迷惑行為のシナリオ場面を3種類作成した。これらの場面はそれぞれ，（1）駅に停車した電車内で，判断対象人物が出入り口の扉付近に立ち続ける（実行）／扉付近から立ち去る（非実行），（2）混雑した電車内で判断対象人物が自分の座る座席の隣にも荷物を置き続ける（実行）／荷物を自分の膝上に動かす（非実行），（3）混雑した電車内で，判断対象人物の背負ったリュックで通り道がふさがる（実行）／リュックを足元に下したために道が空く（非実行），となっている。これらに判断対象人物の迷惑に関する3種類の理解の有無を組み合わせた，合計18種類のシナリオを作成した。それぞれの条件における各シナリオの内容を以下に示す。

## 理解あり・非実行

### ドア前
工藤さんは友人から次のような愚痴を聞いた。友人が電車から降りようとした際に，扉の前に立って動かない人がいたという。電車から降りもしないのに，そんな場所に立っている人が邪魔で，工藤さんの友人は非常に不愉快な思いをしたそうだ。
翌日，工藤さんは電車に乗って乗車口に立っていた。自分が降りる一つ前の駅に停まった時に，電車から降りようとしている人が工藤さんに近づいてきた。そして，昨日の友人の愚痴を思い出した。「このまま扉付近から動かなければ，この人は不快な気持ちになるに違いない」。工藤さんはそう考えて乗車口からどいた。そのため，電車から降りようとしていた人はスムーズに降りることができた。

### 荷物放置
「席が空いていないのに，自分の隣にも荷物を置く奴，邪魔」。最近，SNS上でこのような話が話題になっていた。これを見た伊藤さんは，混雑した電車内で隣の席にも荷物を置くことで，他の人を不愉快な気持ちにさせるのだと十分に理解した。
後日，伊藤さんは電車内で座席に座り，隣の席にも荷物を置いていた。すると，ある駅でたくさんの人が乗り込んできた。たちまち周りの席は全て埋まり，空席を探す人もいた。伊藤さんは先日SNSで話題になっていたことを思い出し，「今隣の席に置いた荷物をどかさなければ，席を探している人が不愉快な思いをするに違いない」と考えた。そして，伊藤さんは荷物を自分の膝の上に置き，座席を探していた人は無事に座ることができた。

### リュック背負い
近年，混雑した電車内での良くない行動として挙げられることが多い行動に，リュックを背負うというものがある。鉄道各社はポスターなどで啓発活動を行い，このようなことをしないように呼び掛けている。こういった活動によって，加藤さんは混雑した電車内でリュックを背負うことは，他の人を不快な気持ちにさせるのだと十分に理解していた。
ある日，加藤さんは混雑した電車内でリュックを背負ったまま立っていた。加藤さんがふと車内に目をやると，自分の後ろを通ろうとしている人に気がついた。このままリュックを背負って立っていれば，この人は不快な気持ちになるに違いないと加藤さんは考えた。そのため，加藤さんはリュックを下して自分の足元に置いた。こうして，加藤さんの後ろを通ろうとしていた人は問題なくそこを通ることができた。


## 理解なし・非実行

### ドア前
工藤さんは友人から次のような愚痴を聞いた。友人が電車から降りようとした際に，扉の前に立って動かない人がいたという。友人はこの人を見て，非常に不愉快な思いをしたそうだ。しかし，工藤さんはこの友人がなぜ不愉快に思ったのかがよく分からず，愚痴を聞き流していた。
翌日，工藤さんは電車に乗って乗車口に立っていた。自分が降りる一つ前の駅に停まった時に，電車から降りようとしている人が工藤さんに近づいてきた。しかし，自分がこのまま乗車口に立ち続けることに何か問題があると工藤さんは思わなかった。また，自分の行動によって他の人が不快な思いをするかどうかについて，工藤さんは全く考えを巡らせなかった。しかし，工藤さんは近くの席がちょうど空いたのに気が付いた。工藤さんは乗車口から動いて席に向かったため，電車から降りようとしていた人はスムーズに降りることができた。

### 荷物放置
「席が空いていないのに，自分の隣にも荷物を置く奴，邪魔」。最近，SNS上でこのような話が話題になっていた。しかし，伊藤さんはこれを見て，「この話を読んだ人はなぜ腹を立てているのだろう」と疑問に思った。
後日，伊藤さんは電車内で座席に座り，隣の席にも荷物を置いていた。すると，ある駅でたくさんの人が乗り込んできた。たちまち周りの席は全て埋まり，空席を探す人もいた。しかし，自分がこのまま隣の席に荷物を置き続けることに何か問題があると伊藤さんは思わなかった。また，自分の行動によって他の人が不快な思いをするかどうかについて，伊藤さんは全く考えを巡らせなかった。しかし，伊藤さんは荷物の中から物を取り出すために，隣の席に置いていた荷物を自分の膝の上に乗せた。そのため，座席を探していた人は伊藤さんの隣に座ることができた。

### リュック背負い
近年，混雑した電車内での良くない行動として挙げられることが多い行動に，リュックを背負うというものがある。鉄道各社はポスターなどで啓発活動を行い，このようなことをしないように呼び掛けている。しかし，加藤さんはこのポスターを見るたびに，リュックを背負うことのどこに問題があるのかが理解できなかった。
ある日，加藤さんは混雑した電車内でリュックを背負ったまま立っていた。加藤さんがふと車内に目をやると，自分の後ろを通ろうとしている人に気がついた。しかし，自分がリュックを背負うことに何か問題があると加藤さんは思わなかった。また，自分の行動によって他の人が不快な思いをするかどうかについて，加藤さんは全く考えを巡らせなかった。しかし加藤さんは，リュックを長時間背負っているのは疲れると思い，リュックを自分の足元に置いた。そのため，加藤さんの後ろを通ろうとしていた人は問題なくそこを通ることができた。


## 情報なし・非実行

### ドア前
ある日，工藤さんは電車内で乗車口に立っていた。駅で電車が停まった際に，工藤さんは乗車口からどいた。そのため，電車から降りようとしていた人はスムーズに降りることができた。

### 荷物放置
ある日，伊藤さんは席の埋まった電車内で座席に座り，隣の席にも自分の荷物を置いていた。駅でたくさんの人が乗り込んできた時，伊藤さんは隣の席に置いていた荷物を自分の膝の上に置いた。そのため，空いている座席を探している人は伊藤さんの隣に座ることができた。

### リュック背負い
ある日，加藤さんは混雑した電車内で，リュックを背中に背負ったまま立っていた。一人の乗客が加藤さんの後ろを通ろうとした時，加藤さんはリュックを下して自分の足元に置いた。そのため，この人は問題なくそこを通ることができた。


## 理解あり・実行

### ドア前
工藤さんは友人から次のような愚痴を聞いた。友人が電車から降りようとした際に，扉の前に立って動かない人がいたという。電車から降りもしないのに，そんな場所に立っている人が邪魔で，工藤さんの友人は非常に不愉快な思いをしたそうだ。
翌日，工藤さんは電車に乗って乗車口に立っていた。自分が降りる一つ前の駅に停まった時に，電車から降りようとしている人が工藤さんに近づいてきた。そして，昨日の友人の愚痴を思い出した。「このまま扉付近から動かなければ，この人は不快な気持ちになるに違いない」。工藤さんはそう考えて扉付近に立ち続けた。そのため，電車から降りようとしている人は，スムーズに降りることができなかった。

### 荷物放置
「席が空いていないのに，自分の隣にも荷物を置く奴，邪魔」。最近，SNS上でこのような話が話題になっていた。これを見た伊藤さんは，混雑した電車内で隣の席にも荷物を置くことで，他の人を不愉快な気持ちにさせるのだと十分に理解した。
後日，伊藤さんは電車内で座席に座り，隣の席にも荷物を置いていた。すると，ある駅でたくさんの人が乗り込んできた。たちまち周りの席は全て埋まり，空席を探す人もいた。伊藤さんは先日SNSで話題になっていたことを思い出し，「今隣の席に置いた荷物をどかさなければ，席を探している人が不愉快な思いをするに違いない」と考えた。そして，伊藤さんは荷物を隣の席に置き続けた。その結果，席を探している人は座席に座ることができなかった。

### リュック背負い
近年，混雑した電車内での良くない行動として挙げられることが多い行動に，リュックを背負うというものがある。鉄道各社はポスターなどで啓発活動を行い，このようなことをしないように呼び掛けている。こういった活動によって，加藤さんは混雑した電車内でリュックを背負うことは，他の人を不快な気持ちにさせるのだと十分に理解していた。
ある日，加藤さんは混雑した電車内でリュックを背負ったまま立っていた。加藤さんがふと車内に目をやると，自分の後ろを通ろうとしている人に気がついた。このままリュックを背負って立っていれば，この人は不快な気持ちになるに違いないと加藤さんは考えた。そして，リュックを背負い続けた。そのため，加藤さんの後ろを通ろうとしていた人は前に進むことができなかった。


## 理解なし・実行

### ドア前
工藤さんは友人から次のような愚痴を聞いた。友人が電車から降りようとした際に，扉の前に立って動かない人がいたという。友人はこの人を見て，非常に不愉快な思いをしたそうだ。しかし，工藤さんはこの友人がなぜ不愉快に思ったのかがよく分からず，愚痴を聞き流していた。
翌日，工藤さんは電車に乗って乗車口に立っていた。自分が降りる一つ前の駅に停まった時に，電車から降りようとしている人が工藤さんに近づいてきた。しかし，自分がこのまま乗車口に立ち続けることに何か問題があると工藤さんは思わなかった。また，自分の行動によって他の人が不快な思いをするかどうかについて，工藤さんは全く考えを巡らせなかった結局，工藤さんは扉付近に立ち続けた。そのため，電車から降りようとしていた人はスムーズに降りることができなかった。

### 荷物放置
「席が空いていないのに，自分の隣にも荷物を置く奴，邪魔」。最近，SNS上でこのような話が話題になっていた。しかし，伊藤さんはこれを見て，「この話を読んだ人たちはなぜ腹を立てているのだろう」と疑問に思った。
後日，伊藤さんは電車内で座席に座り，隣の席にも荷物を置いていた。すると，ある駅でたくさんの人が乗り込んできた。たちまち周りの席は全て埋まり，空席を探す人もいた。しかし，自分がこのまま隣の席に荷物を置き続けることに何か問題があると伊藤さんは思わなかった。また，自分の行動によって他の人が不快な思いをするかどうかについて，伊藤さんは全く考えを巡らせなかった。結局，伊藤さんは隣の席に荷物を起き続けた。そのため，座席を探していた人は座席に座ることができなかった。

### リュック背負い
近年，混雑した電車内での良くない行動として挙げられることが多い行動に，リュックを背負うというものがある。鉄道各社はポスターなどで啓発活動を行い，このようなことをしないように呼び掛けている。しかし，加藤さんはこのポスターを見るたびに，リュックを背負うことのどこに問題があるのかが理解できなかった。
ある日，加藤さんは混雑した電車内でリュックを背負ったまま立っていた。加藤さんがふと車内に目をやると，自分の後ろを通ろうとしている人に気がついた。しかし，自分がリュックを背負うことに何か問題があると加藤さんは思わなかった。また，自分の行動によって他の人が不快な思いをするかどうかについて，加藤さんは全く考えを巡らせなかった。結局，加藤さんはリュックを背負い続けた。そのため，加藤さんの後ろを通ろうとしていた人は前に進むことができなかった。

## 情報なし・実行

### ドア前
ある日，工藤さんは電車内で乗車口に立っていた。駅で電車が停まった際に，工藤さんはそのまま扉付近から動かずに立っていた。そのため，電車から降りようとしていた人はスムーズに降りることができなかった。

### 荷物放置
ある日，伊藤さんは席の埋まった電車内で座席に座り，隣の席にも自分の荷物を置いていた。そのため，座席を探していた人は席に座ることができなかった。

### リュック背負い
ある日，加藤さんは混雑した電車内で，リュックを背中に背負ったまま立っていた。そのため，加藤さんの後ろを通ろうとしていた人はそこを通ることができなかった。

