---
title: "Study2 Discussion"
link-citations: yes
editor_options:
  chunk_output_type: console
output:
  bookdown::html_document2: default
  bookdown::word_document2:
    reference_docx: "/home/rstudio/NuisanceStudy/reference/document_template.docx"
suppress-bibliography: yes
# bibliography: "/home/rstudio/NuisanceStudy/reference/references.bib"
# csl: "/home/rstudio/NuisanceStudy/reference/apa.csl"
---

本予備的研究では，研究1で使用した能力と温かさの評価項目を修正したうえで，研究1の追試を行った。また，判断対象人物の非人間化・行動予測・社会的距離・非難を検討した。判断対象人物の温かさと能力の評価では，研究1の結果が追認され，仮説1と2は支持された。動物的非人間化に関しては，実際に測定されたものが人物の全体的な望ましさを反映したものであると考えられたため，仮説3が支持されたのかどうかの判断は保留とした。また，迷惑行為者への社会的距離の確保と非難が増大する過程で，行為者をより冷たく，将来的に迷惑行為をしやすいと判断することを媒介する効果は，行為者が迷惑を理解している場合に限定されたことから，仮説4と5も支持された。なお，迷惑を理解していない人物が迷惑行為をした場合に，社会的距離と非難の増大に至る媒介効果が認められなかったからといって，このような人物が否定的な評価を免れるわけではない。Table S\@ref(tab:make-sum-table-s2) から，理解なし条件では迷惑行為の有無に関わらず，全般的に否定的評価が下されることが分かる。このことは，無神経であること自体が否定的評価を生み，そのような人物に対しては実際の行動が参照されにくいことを示唆する。

本予備的研究を踏まえ，研究2では非人間化の尺度を修正する必要がある。非人間化の測定に，判断対象の望ましさも反映されてしまうことは，これまでにも指摘されてきた [e.g., @enock2021Noconvincing]。本予備的研究ではこの問題に対処するため，事前に非人間的性質を反映する程度とともに，望ましさの程度も確認されていた特性語の中から，望ましさの高いものと低いものを同数ずつ使用した。これら特性語が当てはまる程度の評定値を平均化することで，判断対象の望ましさに基づく評価が相殺されることを期待した。しかし，特性語の当てはまりの良さの大部分が判断対象の望ましさによって決定される場合，この方法では判断対象を非人間化する程度をほとんど反映できない。この問題に対処するためには，判断対象の望ましさによって当てはまりの良さが左右される程度の小さい特性語を用いて，非人間化を測定する必要がある。研究2では，望ましさが中程度の特性語を用いることで，この問題に対処する。
