---
title: "Master General discussion"
output:
  bookdown::word_document2:
    reference_docx: "/home/rstudio/NuisanceStudy/reference/document_template.docx"
  bookdown::gitbook: default
link-citations: yes
editor_options:
  chunk_output_type: console
# bibliography: "/home/rstudio/NuisanceStudy/reference/references.bib"
# csl: "/home/rstudio/NuisanceStudy/reference/apa.csl"
---

本研究の目的は，何が迷惑行為に当たるのかを理解していない無神経な人物は，無神経であること自体を以て否定的に評価されるのかを検討することであった。研究1と研究2，および予備的研究を通して，たとえ迷惑行為をしなかったとしても，無神経であること自体に否定的な評価が向けられることを示した。研究1では，無神経な人物に対する温かさと能力についての印象を検討した。その結果，無神経な人物の実際の行動は参照されにくく，むしろ無神経であること自体によって否定的な印象を向けられることが明らかになった。研究2とその予備的研究では，検討対象に人物への態度と人間性の評価を加えた。ここでも，無神経な人物の実際の行動は，無神経であることよりも考慮されにくく，むしろ無神経であること自体が否定的な対人評価を生むことが示された。

本研究の結果から，深刻な害を発生させるわけではない迷惑行為に対して，社会問題とされるほどに人々が否定的に反応する理由の1つが，迷惑行為者が自身の悪影響を理解しておらず，その意味で無神経であるように見えることが不快感を生むためであると考えられる。これまでに迷惑行為が否定的に評価される原因を検討した研究は，迷惑行為自体の性質に着目してきた [例えば @yoshida1999meiwaku1]。しかし，本研究は迷惑行為に対する評価が行動そのものよりもむしろ，行為者の心的状態の評価に基づくことを示している。これは，他者に関する対人認知を行う過程の中で，その心的状態を推論することが大きな影響力を持つとする仮説 [@reeder2009mindreading1] とも符合する。したがって本研究は，迷惑行為に対する属人的評価を検討することが有効であることを示す。

また，本研究は迷惑行為研究以外にも，心的状態の推論に基づく対人認知の研究にも寄与する。心的状態の推論が対人認知に及ぼす影響を検討したこれまでの研究の多くは，他者に対する積極的な危害意図を持つ人物の印象や道徳性が否定的に評価されることを示してきた [例えば @hirozawa2020Intentionmatters; @inbar2012BenefitingMisfortune]。その一方で， @gromet2016PleasureAnother や @krull2008Smilewhen， @schwartz2023itgood  といった，他者への配慮や親切心などの望ましい心的状態が欠如した人物に対して，人々がどのような評価を下すのかを検討した研究は限られている。特に本研究のように，実際の逸脱行為を伴わなくとも，望ましい心的状態の欠如自体が否定的評価を生じさせることを示した研究は少ない。これらの類似研究と比較した時の本研究の特徴は，無神経であること自体によって冷たい人物だと評価され，否定的な態度を向けられることに加え，能力次元の評価は他者への積極的な危害意図を持つ人物以上に低くなり，その反映として知的能力に欠けた動物として非人間化されることを示した点にある。これにより，積極的な悪意を抱かずとも，無神経であることだけでも否定的評価の対象となることが明らかとなった。

<br>

## 本研究の限界と今後の展望 {.unnumbered}

本研究の限界として三点を挙げる。第一に本研究では，迷惑行為が実行されなかったとしても，無神経な人物への否定的評価は緩和されにくいことを示すことで，無神経であること自体が否定的評価を生むことを示した。しかし，迷惑行為者への評価を形成する過程で，この人物が迷惑の影響を理解していないことがどのようにして否定的評価を生むのかは明らかにできなかった。そのため，判断対象人物が迷惑行為を実行した条件で，迷惑への理解の有無の条件間の差が有意ながらも小さかったことから，迷惑行為者の評価にはその行為者の心的状態があまり反映されず，むしろその評価は主に迷惑行為を実行したという情報に基づいていたという解釈もできるかもしれない。その一方で，無理解かつ実行条件での評価から，迷惑行為をしたことに基づく評価を差し引いて残ったのが，無理解かつ非実行条件における評価だと考えることができる。その場合，これら2条件間の差異の小ささを鑑みるに，無神経な行為者への評価の実態の大半は，無神経であること自体に基づいているとも考えられる。しかし，無神経な迷惑行為者への対人認知のメカニズムは十分に明らかでなく，今後のさらなる検討が必要である。

第二に，本研究で用いた指標の評価結果に概ね同様の傾向がみられたのは，いわゆる「ハロー効果」やキャリーオーバー効果に過ぎないかもしれないという点を考慮すべきである。研究2の機械的非人間化の結果は，この評価が単なる人物の全体的な望ましさだけで説明できないことを示唆するが，証拠は十分でない。今後の研究では，例えば @bastian2013RolesDehumanization が行ったように人物の全体的な望ましさを測定し，これを統計的に統制したうえで，興味のある評価指標に対して無神経であることが及ぼす影響を検討することが有用だろう。

第三に，本研究の一般化可能性についても，さらなる検討が必要である。本研究で用いた迷惑行為は，駅・電車内での迷惑行為ランキングの上位に位置しており，広く認知されているものである。したがって，他の状況下での迷惑行為や，認知度があまり高くない迷惑行為に関しても，それを迷惑だと理解していない人物への評価を検討する必要がある。

本研究は幅広い評価指標を用いて，無神経であること自体が否定的に評価されることを3つの研究に渡って示した。このことは，迷惑行為者に対する否定的評価が，行動よりもむしろ望ましくない心的状態に基づいていることを示唆している。今後は，無神経さに向けられる否定的評価が生じる過程を明らかにするとともに，本研究の一般化可能性について検討を重ねる必要があるだろう。
