---
title: "Master Introduction"
output:
  bookdown::word_document2: 
    reference_docx: "/home/rstudio/NuisanceStudy/reference/document_template.docx"
  bookdown::gitbook: 
link-citations: yes
editor_options:
  chunk_output_type: console
# bibliography: "/home/rstudio/NuisanceStudy/reference/references.bib"
# csl: "/home/rstudio/NuisanceStudy/reference/apa.csl"
suppress-bibliography: yes
---

自分は降りもしないのに，電車の出入口付近に立ち続けて周囲の人の乗降を妨げる人物は，迷惑な人物であると否定的に評価される。このような迷惑行為は一般に，犯罪行為のように特に大きな危害を生むわけではない。しかし，それが否定的評価を生む理由は十分に明らかになっていない。この問題に対して本研究は，迷惑行為者が無神経であるように見えることに着目する。これまでに，迷惑行為の特徴の1つとして，無神経な行為とみなされることが示唆されている [@kitaori2008KY]。無神経であるとは，周囲に対する自身の悪影響について考えを巡らせず，結果的にその悪影響を理解していない状態である [@kitaori2017rule]。しかし @kitaori2008KY は，迷惑だという判断と，その行動を無神経だと思うことの関連を間接的に示すことにとどまっており，無神経であることが実際に迷惑行為者への否定的評価を生むのかを明らかにしていない。そこで本研究では，迷惑行為者が無神経であるように見えること自体が，否定的評価を生じさせることを検討する。

無神経な人物に対する評価を検討するために，本研究では心的状態の推論に基づく対人認知に着目する。これまでに，他者へ危害を及ぼさずとも，望ましくない心的状態にある人物は否定的に評価されることが指摘されている [例えば @hirozawa2020Intentionmatters; @inbar2012BenefitingMisfortune]。特に，迷惑行為という他者への実害が小さい，あるいはまったく実害を生じさせない行動をとった人物が否定的に評価される場合，その評価は主に，迷惑行為者が無神経という望ましくない心的状態であることに対して向けられると予想する。これを検証するために，シナリオ実験を用い，判断対象人物が迷惑行為の悪影響を理解しているのかどうか，および他者に実際に迷惑をかけたのかどうかを操作する。特に，迷惑行為をせずとも何が周囲の迷惑になるのかを理解していない人物に対する評価に着目することで，無神経であること自体に向けられる否定的評価を示すことを目的とする。

<br>

## 基本2次元を軸とした対人認知 {.unnumbered}

無神経な人物に関する判断を調べるに当たって，本研究では当該人物に対する印象・態度・人間性に関する評価の3点について検証を行う。まず印象については，印象形成の基本次元として数多くの先行研究 [レビューとして @abele2021Navigatingsocial] が用いてきた「温かさ」と「有能さ」の次元に着目する。親切さや正直さといった人物の温かさを表す特性は，社会の中で他者と協力的な関係を築き，他者の福利に配慮してこれを守ることに関連するとされている [@abele2021Navigatingsocial]。この次元の評価は，判断対象人物の迷惑に対する理解の有無と，実際の行動によって異なると考えられる。迷惑行為の悪影響を理解している場合，迷惑行為をした人物は，他者に害を及ぼすことへの願望を抱いていると推測できるため [@laurent2015influencedesire]，冷たいと評価されるだろう [@reeder2002Inferencesmorality]。そして，悪影響を理解して迷惑行為をしなかった人物は，他者への害を意図的に防止したという意味で，温かいと評価されるだろう。一方で迷惑行為の悪影響を理解していない無神経な人物は，迷惑行為の有無にかかわらず，他者の福利への配慮が欠けていること自体によって冷たいと評価されるだろう。実際，逸脱行為者が自身の行動を間違ったものだと認識していないことで，その逸脱者には人物の温かさの重要な要素である道徳性が欠けていると評価されることが示されている [@schwartz2023itgood]。したがって，判断対象人物が無神経であれば，行為にかかわらず冷たいと評価されるために，迷惑行為実行の有無による冷たさの評価の変化量は小さくなると予想する。同時に，無神経であること自体によって人物が冷たいと評価されるならば，迷惑行為をしない場合であっても，その迷惑を理解していない無神経な人物は，その迷惑を理解していた人物と比べ，冷たいと評価されると予想する。

「有能さ」の次元では，無神経な人物は迷惑行為の影響を理解している人物よりもネガティブに評価されると思われる。人々は自身の意見が客観的であり，理性のある他者ならば自身と同じ意見を共有していると考えやすいナイーブ・リアリズムを持つ [@ross1995PsychologicalBarriers]。そのため，自身のものと一致しない考えを持つ他者に対して，理解して当然のことを理解しておらず，知的能力に劣ると評価する傾向がある [@hartman2022PeopleSee; @sammut2015spiralconflict]。特に迷惑行為を目の当たりにした者は，無神経な人物に対し，何が迷惑であるのかといった理解して当然のことを理解していないと評価するだろう。そのため，無神経な人物は知的能力に劣ると評価されると予想する。

第二に態度の観点からは，相手の将来の行動に関する予測を介した社会的距離の確保と非難を検討する。人物に対する態度の形成に将来の行動についての予測が関与すると考えられる理由は，他者に対する態度の形成が，その他者に対する予測と対処の一環だと考えられるためである [@fiske1992Thinkingdoing]。特に，有害な行動を実行するかどうかの予測は，その人物が冷たいのかどうかによってなされると考えられている [@fiske2007Universaldimensions]。そのため，人は判断対象人物を冷たいと評価することで，それに応じて将来的により高い確率で有害な行動の一種である迷惑行為を実行しやすいと予測し，それに対処するための態度を形成するだろう。そしてその判断対象人物と社会的距離を置き，その人物を非難すると考えられる。実際，有害な行動をとると予測される人物から，人は社会的距離を置こうとする [@corrigan2003attributionmodel; @martin2000FearLoathing]。また，反社会的な考えや心的状態を持つ人物は非難されやすい [@cushman2008Crimepunishment; @patil2017behavioralneural]。このような人物が非難されやすい理由は，非難には今後予測される他者の有害な行動を予防する機能があると考えられているためである [@martin2016AdaptiveLogic]。したがって，将来迷惑行為を実行しやすいと予測される人物ほど，より強い非難を受けると考えられる。

第三に，人間性の評価として非人間化を検討する。その理由は，無神経な人物へのより侮蔑的な評価を明らかにするためである。人間性には，理性的であるなどの動物と比較した時に人間にのみ当てはまる特性（Uniquely Human: UH）と，感情的であるなどの機械と比較した時に人間にのみ当てはまる特性（Human Nature: HN）の2つの側面があるとされている [@haslam2006DehumanizationIntegrative]。このうち，UHを否定することは動物的非人間化であり，HNを否定することは機械的非人間化である。特に，自身の行動によって生じる結果を認識して物事の善悪を判断する能力である，行為者性（agency）が欠如していることは，動物的な性質と関連付けられやすい [@gray2007DimensionsMind]。迷惑行為によってどのような結果が生じるのかを理解せず，その悪質性を認識していない無神経な人物は，この行為者性が欠如していると評価されると考えられる。また，知的能力が欠如しているとみなされた人物は動物のようなものとして非人間化される [@loughnan2007AnimalsAndroids]。これらの理由から，迷惑行為の悪影響を理解していないことで，その人物は理性の欠けた動物として非人間化されると予想する。

<br>

## 本研究の概要 {.unnumbered}


本研究は，無神経な人物は，たとえ誰にも悪影響を及ぼさなかったとしても，無神経であること自体を以て否定的に評価されることを，無神経な人物への印象・態度・人間性の評価の観点から検証した。2つの研究と1つの予備的研究を通してシナリオ実験を行い，判断対象人物が，迷惑行為が周囲への迷惑になると理解しているかどうか，および実際に迷惑行為を実行したのかどうかを操作し，判断対象人物への評価を測定した。本研究では特に，迷惑を理解していない人物と理解している人物の間で，迷惑行為をしたかどうかによる否定的評価の変化量を比較した。この比較により，迷惑を理解していない人物への評価の多くは迷惑を理解していないこと自体に基づいており，このような人物への評価は迷惑行為の有無によって変化しにくく，いずれの場合でも否定的に評価されることを検証した。本研究で検証する仮説は以下の通りである。

1.  迷惑行為をした人物の方が，しなかった人物よりも冷たいと評価される。この効果は，判断対象人物が迷惑行為の悪影響を理解していない場合の方が，理解している場合よりも小さい。これと同時に，迷惑行為をしなかった場合，迷惑を理解している人物よりも理解していない人物の方が冷たいと評価される。

2.  迷惑行為の有無にかかわらず，迷惑を理解していない人物の方が，理解している人物よりも能力が低いと評価される。

3.  迷惑行為の有無にかかわらず，迷惑を理解していない人物の方が，理解している人物よりも動物的に非人間化される。

4.  迷惑行為をした判断対象人物をより冷たいと評価し，この評価に応じて将来的に迷惑行為をより実行しやすいと予想し，この予想を媒介してこの人物から社会的距離を空ける。しかしこの効果は，判断対象人物が迷惑を理解していない場合では小さくなる。

5.  迷惑行為をした判断対象人物をより冷たいと評価し，この評価に応じて将来的に迷惑行為をより実行しやすいと予想し，この予想を媒介してこの人物をより強く非難する。しかしこの効果は，判断対象人物が迷惑を理解していない場合では小さくなる。

これらのうち，研究1では仮説1と仮説2を検証する。実験デザインを変更した研究2と，その予備的研究${}^5$では，これらの仮説に加え，仮説3から仮説5を検証する。
